### ISSUE TITLE
Remove edumedia-sciences.com special handling and Flash support

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#110]
There is code in the `UBBoardController` for special handling of content from edumedia-sciences.com. This is no longer necessary. Edumedia does no longer provide ZIP files with flash content, but HTML5 content. This content can easily be placed on the board by visiting the web page with the integrated browser and creating a widget using the web content capturing tool.

Note however that you need an account to show the content for longer than a couple of seconds.

Remove the obsolete code.

**Comment by letsfindaway** [comment]
> Along with this, I would strongly recommend to remove all code related to Flash Player. Chromium and therefore also `QWebEngine` is blocking any Flash content since January 2021. All workarounds are unsupported and create a security risk.

@kaamui: Any opinion on this? I saw that two years ago in 4bdecc834c63498128d6de901d45bc61ad7f99cb you just deactivated Flash content but did not remove it in order to be able to re-enable it later. But now I think re-enabling is not anything I would like to see for OpenBoard in the future.

**Comment by kaamui** [comment]
In January 2021, I was contacted by volunteers in Haïti that were helping to rebuild some schools and wanted to switch from OpenSankoré to OpenBoard at the same time. They had a lot of documents, used in class, that were entirely based on flash content. I gave them a demo-version of OpenBoard where it was still available, and where I was using something like https://github.com/swf2js/swf2js if I remember well, to make their documents still run correctly, giving them time to prepare the transition from flash content to html5 content. @fcmoses was helping them, I wonder where they are at now.  

So, as I explained in the commit message, I didn't go further in order to make it easier for anyone trying to re-enable it. I won't re-enable it, of course, in the main project, but you have to take into account that some parts of the world are not moving to new techs and libs at the same speed we can.

As I told you before, I'm not a big fan of deleting everything the second something seems to no longer be useful, because of my experience of such cases. I don't think I can anticipate every change of context, or every use case, and OpenBoard is a big project, used all over the world, not always under the same conditions that you can find in Switzerland or Germany. 

For edumedia content, I was not aware of it. Indeed it could be removed.

**Comment by letsfindaway** [comment]
Back from a few days of relaxing vacations! Here I am again ;)

Ok, got it. I will just concentrate on the edumedia handling.

**Comment by letsfindaway** [comment]
closed as PR was merged
