### ISSUE TITLE
Size of left and right palette changes

### ISSUE THREAD

**Issue by letsfindaway** [letsfindaway/OpenBoard#125]
I started showing the left and/or right palette. Then I resized them to my needs. After closing and re-opening OpenBoard, the palette was resized to some fixed width.

**Comment by letsfindaway** [comment]
This is caused by calling `controlWidget->showNormal();` in the display manager due to my "fix" of screen change handling. This call is too early, and the sizes of the widgets are still unknown.

**Comment by letsfindaway** [comment]
When resetting the geometry with `setGeometry(QRect())` the size of the widgets collapses to a default size. This triggers a resize event which calls `UBRightPalette::updateMaxWidth()`. This reduces the size of the palette.

**Comment by kaamui** [comment]
If I remember well, we are talking about rare use cases, depending (on Ubuntu/Gnome only), on which screen is the primary one (the one having the "Activities" toolbar), with screens ordered from right to left. And I'm not a 100% sure about the following assertion, but I think non of these placement issues that are not fixed by simply restarting so... 

It's not worth it, imo. Actually, in Geneva schools, we have zero schools where it is the case. I think the action should be to add under the input that changing displays may need that OpenBoard restarts for them to be taken into account correctly.

**Comment by letsfindaway** [comment]
Suppressing resize events while resetting geometry fixes this problem. Associated PR was merged.
