### ISSUE TITLE
I didn't find the QT version

### ISSUE THREAD

**Issue by Messiaslogia** [letsfindaway/OpenBoard#85]
![image](https://user-images.githubusercontent.com/63260830/169380418-c33c228c-a98b-41e9-8e95-b38b1bcbcec4.png)

Good afternoon. I'm having trouble finding the Qt 5.15.3 version (I used version 5.15.2) but when completing the compilation the program does not open.

I git merged from 1.7-dev to the letsfindaway branch (rework -display...)

Could you shed some light on this case? Or even let me know if with version 5.15.2 I should start the software normally?

Thank you very much. I really like your software.

**Comment by letsfindaway** [comment]
Even if the commit message suggests, the build and package scripts of kaamui just use the standard Qt version of the Linux distribution, in this case it is 5.15.3 on Ubuntu 22.04.

OpenBoard should compile and work fine with any Qt version starting from Qt 5.12. You should avoid Qt 5.12.2 due to bug https://bugreports.qt.io/browse/QTBUG-88309, but anything else will do.

If you have an error like "program does not open", then please start it from a console. Here you will most probably find more information about the problem.

BTW: You're on Linux, right? What distribution? It is always helpful to give some information about your environment.

And, please be aware that my branch `rework-displaymanager` was recently merged into `1.7-dev` (see https://github.com/OpenBoard-org/OpenBoard/pull/598), so you will now have that feature by checking out 1.7-dev`.

**Comment by Randomizando3** [comment]
Hi, the same thing happens to me, but I'm compiling on windows 10. At the moment would it need to be compiled only for linux  distributions?

**Comment by letsfindaway** [comment]
> Hi, the same thing happens to me, but I'm compiling on windows 10. At the moment would it need to be compiled only for linux distributions?

For building on WIndows please follow the instructions in the wiki of the upstream project: https://github.com/OpenBoard-org/OpenBoard/wiki/Build-OpenBoard-on-Windows-10.

**Comment by letsfindaway** [comment]
probably answered, stale since 3 weeks
